### PR TITLE
1984 - TeamSpeak Registration Deletion Fix

### LINKED ISSUE #1984: TeamSpeak Exception
## Error in Core

**TeamSpeak3_Adapter_ServerQuery_Exception** in **GET /mship/manage/teamspeak/21991/delete**
ok

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/core/errors/5fb4e504fb99360017c20457?event_id=5fb530f60063ea7ea9e80000&i=gh&m=ci)

## Stacktrace

    app/Models/TeamSpeak/Registration.php:63 - App\Models\TeamSpeak\Registration::delete
    app/Http/Controllers/TeamSpeak/Registration.php:59 - App\Http\Controllers\TeamSpeak\Registration::getDelete
    app/Http/Controllers/BaseController.php:40 - App\Http\Controllers\BaseController::App\Http\Controllers\{closure}
    app/Http/Middleware/RedirectToIntended.php:23 - App\Http\Middleware\RedirectToIntended::handle
    app/Traits/Middleware/RedirectsOnFailure.php:48 - App\Http\Middleware\UserMustReadNotifications::handle
    app/Http/Middleware/DenyIfBanned.php:27 - App\Http\Middleware\DenyIfBanned::handle
    app/Traits/Middleware/RedirectsOnFailure.php:48 - App\Http\Middleware\MandatoryPasswords::handle
    app/Http/Middleware/RecordLoginInfo.php:39 - App\Http\Middleware\RecordLoginInfo::handle
    app/Http/Middleware/TrackInactivity.php:43 - App\Http\Middleware\TrackInactivity::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/core/errors/5fb4e504fb99360017c20457?event_id=5fb530f60063ea7ea9e80000&i=gh&m=ci)

*Created by Calum Towers via Bugsnag*

### PR DESCRIPTION
**Pull request by CalumTowers**
This PR will be easier to review with the stack trace in #1984 
The TeamSpeak library is throwing an exception incorrectly.

When removing a registration, we first check that there is a privilege key in our system (stored in `teamspeak_confirmation`) associated with the registration being deleted.

We then delete it from TeamSpeak (`$tscon->privilegeKeyDelete($this->confirmation->privilege_key);`) and then remove it from our database (`$this->confirmation->delete();`).

The first line is throwing a `TeamSpeak3_Adapter_ServerQuery_Exception` exception even though the exception message is `ok` and the privilege key is removed on TeamSpeak. The result it that the privilege key isn't removed from our system and the registration also is not removed - throwing an error to the user.

This is not the proudest code I have ever written, but it should fix the problem for now. We need to decide on the future of TeamSpeak and if we are retaining it, it is highly likely a lot of this needs a full re-write to tidy it up...

Resolves #1984

### CODE REVIEW

File: app/Models/TeamSpeak/Registration.php [hunk 1]
```diff
@@ -59,8 +60,16 @@ public function delete($tscon = null)
             if ($tscon == null) {
                 $tscon = TeamSpeak::run('VATSIM UK Registrations');
             }
+
             if ($this->confirmation) {
-                $tscon->privilegeKeyDelete($this->confirmation->privilege_key);
+                try {
+                    $tscon->privilegeKeyDelete($this->confirmation->privilege_key);
+                } catch (TeamSpeak3_Adapter_ServerQuery_Exception $e) {
+                    if ($e->getMessage() === 'ok') {
```
Comment (AxonC) [inline app/Models/TeamSpeak/Registration.php:68]: Possibly worth adding a comment above here as per the description in the PR, if we ever come to this again and go 'wtf'

**Review by AxonC — APPROVED** [review]

File: app/Models/TeamSpeak/Registration.php (hunk 1 above)
Comment (CalumTowers) [reply app/Models/TeamSpeak/Registration.php:68]: Git blame will help us find this... Although I hope I never have to touch it again 🙃
