### PR TITLE
Fix app/helpers.php name parsing exceptions

### LINKED ISSUE #735: ErrorException in app/helpers.php:42
## Error in VATSIM-UK/Core

**ErrorException** in **app/helpers.php:42**
trim() expects parameter 1 to be string, object given

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5862a9cf1e51a96a2ae98b21?event_id=5862a9cfd7da7911008a5379)

## Stacktrace

    app/helpers.php:42 - Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    app/helpers.php:42 - format_name
    app/Models/Mship/Account.php:1305 - App\Models\Mship\Account::setNameFirstAttribute
    app/Models/Mship/Account.php:261 - App\Models\Mship\Account::findOrRetrieve
    app/Modules/NetworkData/Console/Commands/DownloadAndParse.php:138 - App\Modules\NetworkData\Console\Commands\DownloadAndParse::parseRecentDownload
    app/Modules/NetworkData/Console/Commands/DownloadAndParse.php:69 - App\Modules\NetworkData\Console\Commands\DownloadAndParse::fire

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5862a9cf1e51a96a2ae98b21?event_id=5862a9cfd7da7911008a5379)

### PR DESCRIPTION
**Pull request by atoff**
This exception was created when findOrRetrieve was called for a non-numeric CID or it was null.

This was mainly occurring when:
- A V/T users specifies their referee's CID as an invalid CID e.g VATUSA1
- The parsing of the recent network data picks up a strange controller session where the CID is null or otherwise invalid.

To fix V/T, home logic was moved until after the input data has been verified.
A failsafe non-numeric catch was implemented in the account's findOrRetrieve method.
A try catch was used in parsing the network data for an account that failed to be made

Closes #735

### CODE REVIEW

File: app/Exceptions/Mship/InvalidCIDException.php [hunk 1]
```diff
@@ -0,0 +1,16 @@
+<?php
+
+namespace App\Exceptions\Mship;
+
+class InvalidCIDException extends \Exception
+{
+    public function __construct()
+    {
+        //
```
Comment (NFarrington) [inline app/Exceptions/Mship/InvalidCIDException.php]: Should call parent constructor or not exist
